name: Pull Request

on:
  pull_request:

jobs:
  test:
    name: Validate PR
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2

    - name: Set up node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: yarn

    - name: Install dependencies
      run: |
        yarn install

    - name: Run tests
      run: |
        yarn test

